export interface AssetEntry { path: string; kind: 'texture' | 'hdr' | 'gltf' | 'glb' | 'fbx' | 'buffer' | 'ktx2'; bytes: number; label: string }

// File sizes weight completion events for image loads that have no byte callback.
// The manifest test checks these sizes against the shipped files.
export const ASSET_MANIFEST: readonly AssetEntry[] = [
  { path: 'textures/terrain-color.png', kind: 'texture', bytes: 67309, label: 'Cores da ilha' },
  { path: 'textures/grass-color.webp', kind: 'texture', bytes: 104780, label: 'Texturas da ilha' },
  { path: 'textures/grass-normal.webp', kind: 'texture', bytes: 122114, label: 'Texturas da ilha' },
  { path: 'textures/grass-roughness.webp', kind: 'texture', bytes: 11912, label: 'Texturas da ilha' },
  { path: 'textures/sand-color.webp', kind: 'texture', bytes: 54014, label: 'Texturas da ilha' },
  { path: 'textures/sand-normal.webp', kind: 'texture', bytes: 90308, label: 'Texturas da ilha' },
  { path: 'textures/sand-roughness.webp', kind: 'texture', bytes: 4632, label: 'Texturas da ilha' },
  { path: 'textures/plaster-color.webp', kind: 'texture', bytes: 45970, label: 'Texturas da ilha' },
  { path: 'textures/plaster-normal.webp', kind: 'texture', bytes: 15202, label: 'Texturas da ilha' },
  { path: 'textures/plaster-roughness.webp', kind: 'texture', bytes: 2430, label: 'Texturas da ilha' },
  { path: 'textures/brick-color.webp', kind: 'texture', bytes: 64772, label: 'Texturas da ilha' },
  { path: 'textures/brick-normal.webp', kind: 'texture', bytes: 76720, label: 'Texturas da ilha' },
  { path: 'textures/brick-roughness.webp', kind: 'texture', bytes: 16992, label: 'Texturas da ilha' },
  { path: 'textures/stone-color.webp', kind: 'texture', bytes: 77598, label: 'Texturas da ilha' },
  { path: 'textures/stone-normal.webp', kind: 'texture', bytes: 48132, label: 'Texturas da ilha' },
  { path: 'textures/stone-roughness.webp', kind: 'texture', bytes: 26524, label: 'Texturas da ilha' },
  { path: 'textures/timber-color.webp', kind: 'texture', bytes: 24442, label: 'Texturas da ilha' },
  { path: 'textures/timber-normal.webp', kind: 'texture', bytes: 15732, label: 'Texturas da ilha' },
  { path: 'textures/timber-roughness.webp', kind: 'texture', bytes: 1924, label: 'Texturas da ilha' },
  { path: 'textures/bark-color.webp', kind: 'texture', bytes: 37584, label: 'Texturas da ilha' },
  { path: 'textures/bark-normal.webp', kind: 'texture', bytes: 102654, label: 'Texturas da ilha' },
  { path: 'textures/bark-roughness.webp', kind: 'texture', bytes: 874, label: 'Texturas da ilha' },
  { path: 'textures/metal-color.webp', kind: 'texture', bytes: 25018, label: 'Texturas da ilha' },
  { path: 'textures/metal-normal.webp', kind: 'texture', bytes: 9502, label: 'Texturas da ilha' },
  { path: 'textures/metal-roughness.webp', kind: 'texture', bytes: 4360, label: 'Texturas da ilha' },
  { path: 'textures/roof-color.webp', kind: 'texture', bytes: 67488, label: 'Texturas da ilha' },
  { path: 'textures/roof-normal.webp', kind: 'texture', bytes: 23378, label: 'Texturas da ilha' },
  { path: 'textures/roof-roughness.webp', kind: 'texture', bytes: 72384, label: 'Texturas da ilha' },
  { path: 'textures/road-color.webp', kind: 'texture', bytes: 98756, label: 'Texturas da ilha' },
  { path: 'textures/road-normal.webp', kind: 'texture', bytes: 113334, label: 'Texturas da ilha' },
  { path: 'textures/road-roughness.webp', kind: 'texture', bytes: 12708, label: 'Texturas da ilha' },
  { path: 'textures/partly-cloudy-sky-1k.hdr', kind: 'hdr', bytes: 1366191, label: 'Céu' },
  { path: 'models/service-pistol/service_pistol_1k.gltf', kind: 'gltf', bytes: 17614, label: 'Pistola' },
  { path: 'models/service-pistol/service_pistol.bin', kind: 'buffer', bytes: 1052048, label: 'Pistola' },
  { path: 'models/service-pistol/textures/service_pistol_diff_1k.jpg', kind: 'texture', bytes: 718216, label: 'Pistola' },
  { path: 'models/service-pistol/textures/service_pistol_arm_1k.jpg', kind: 'texture', bytes: 921086, label: 'Pistola' },
  { path: 'models/service-pistol/textures/service_pistol_nor_gl_1k.jpg', kind: 'texture', bytes: 588720, label: 'Pistola' },
  { path: 'models/m700/m700.fbx', kind: 'fbx', bytes: 638732, label: 'Rifle' },
  { path: 'models/m700/color.webp', kind: 'texture', bytes: 130470, label: 'Rifle' },
  { path: 'models/m700/normal.webp', kind: 'texture', bytes: 117862, label: 'Rifle' },
  { path: 'models/m700/metalness.webp', kind: 'texture', bytes: 59682, label: 'Rifle' },
  { path: 'models/m700/ao.webp', kind: 'texture', bytes: 73602, label: 'Rifle' },
  { path: 'models/m700/roughness.webp', kind: 'texture', bytes: 110016, label: 'Rifle' },
];
